### ISSUE TITLE
Tracking issue for server stability (old 1)

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#1100]
Here I collect open issues related to zellij server stability, meaning problems that may cause sessions to crash or become otherwise unuseable. Currently, I limit this list to issues where active work can get lost, e.g. a new session crashing directly at startup is out of scope.

### Server crashes
- [x] https://github.com/zellij-org/zellij/issues/1551
- [x] https://github.com/zellij-org/zellij/issues/1423
- [x] https://github.com/zellij-org/zellij/issues/1323
- [x] https://github.com/zellij-org/zellij/issues/1040
- [x] https://github.com/zellij-org/zellij/issues/1340
- [x] https://github.com/zellij-org/zellij/issues/1346
- [x] https://github.com/zellij-org/zellij/issues/1108
- [x] https://github.com/zellij-org/zellij/issues/1029
- [x] https://github.com/zellij-org/zellij/issues/805
- [x] https://github.com/zellij-org/zellij/issues/882
- [x] https://github.com/zellij-org/zellij/issues/816
- [x] https://github.com/zellij-org/zellij/issues/528
- [x] https://github.com/zellij-org/zellij/issues/929
- [x] https://github.com/zellij-org/zellij/issues/1217
- [x] https://github.com/zellij-org/zellij/issues/1241
- [x] https://github.com/zellij-org/zellij/issues/1050
crash on new tab open, most likely resolved after clearing plugin cache
To avoid this problem, use `cargo make run` instead of `cargo run` for test builds.
- [x] https://github.com/zellij-org/zellij/issues/979

 ### Inaccessible session / corruption
- [x] https://github.com/zellij-org/zellij/issues/1209

I suggest to keep comments to their respective issues instead of here, to keep this tracking issue "clean" of crash details.

**Feel free to ping me in other / new issues if I should update this list.**

**Comment by raphCode** [comment]
Ideally, we can fix panics / crashes before they occur to users.
For this, we should make most / all server code that interacts with syscalls and the wasm plugin system fail gracefully instead of panicing.
The rest of the bugs are probably internal logic bugs anyway

I am not sure on how to approach that - should I spam a bunch of new issues for all the potentially offending code locations I can find?

**Comment by jaeheonji** [comment]
First of all, I personally think that the key to this problem is the unexpected `unwrap` code.

The intentional `panic` code is a necessary part (currently about 10-15 lines of the entire code) and I'm working on an error-reporting system for it.

However, verifying all unwrap code is very difficult. So "ideally" we should fix the error before the user sees it, but in the end, it's natural to get feedback from users and fix it.

So I think the purpose of this issue is to gather stability-related issues for new issues.
And we'll just have to add the problems we find naturally in developing.

**Comment by raphCode** [comment]
The new issue is #1568
