### ISSUE TITLE
Tracking issue for server stability

### ISSUE THREAD

**Issue by raphCode** [zellij-org/zellij#1568]
Here I collect open issues related to zellij server stability, meaning problems that may cause sessions to crash or become otherwise unuseable. Currently, I limit this list to issues where active work can get lost, e.g. a new session crashing directly at startup is out of scope.

This is the second list, the old one being #1100

### Server crashes
- [ ] https://github.com/zellij-org/zellij/issues/1532
- [ ] https://github.com/zellij-org/zellij/issues/1350

 ### Inaccessible session / corruption
- [ ] https://github.com/zellij-org/zellij/issues/1063
- [ ] https://github.com/zellij-org/zellij/issues/1255

**Feel free to ping me in other / new issues if I should update this list.**

**Comment by fansari** [comment]
Hope this will be fixed. It is not so bad as it was in the beginning but I still have to kill zellij and start again.  Then I typically see two time "zellij attach" when running "ps -ef | grep zellij". I kill them and start again - but of course it always takes time to recreate all stuff as it was before.

**Comment by kabirz** [comment]
Had same issue in version 0.31.1

**Comment by dougg0k** [comment]
Why not put an auto error reporting option that does not collect anything personal?
