### ISSUE TITLE
Meta issue: Beta version

### ISSUE THREAD

**Issue by imsnif** [zellij-org/zellij#194]
# Goals of the beta version
Upon release of this version, Zellij should be stable and have enough features to be the daily driver of those who wish to contribute to its development. Be they active developers or enthusiasts who believe in the future of this app.

This issue tracks all the work that needs to be done to achieve this goal. 

### Stability level
There should be no crashes except in extreme situations.

### Compatibility level
There should be no bugs that require the pane to be re-opened in order to fix: resizing in order to fix is fine for this version.

### Performance level
The performance should not be annoying.

### Features
- [x] supports linux and macos
- [x] tab bar (https://github.com/zellij-org/zellij/issues/166)
- [x] react to terminal window resizes (https://github.com/zellij-org/zellij/issues/34 and https://github.com/zellij-org/zellij/issues/122)
- [x] plugin system documentation (https://github.com/zellij-org/zellij/issues/193)
- [x] status bar should behave properly (https://github.com/zellij-org/zellij/issues/192)

### Bugs
- [x] https://github.com/zellij-org/zellij/issues/184
- [x] https://github.com/zellij-org/zellij/issues/167
- [x] https://github.com/zellij-org/zellij/issues/43

**Comment by imsnif** [comment]
::tada::
