### ISSUE TITLE
Action Requests Overview

### ISSUE THREAD

**Issue by a-kenji** [zellij-org/zellij#338]
This issue is meant to be a thread for suggesting / requesting / giving an overview of new action features for zellij. An action can be bound to a keybinding and then launched.

- [ ] Implement functionality propagate (sync) all panes either type or paste text #302
- [ ] How do I programmatically open couple of panes and run command on them #284
- [ ] Feature: move current pane to new tab #196
- [ ] Feature: rotate pane locations #165
- [ ] Feature: move panes directionally #164

Improving Action Handling:

- [ ] Feature: mouse support #175

Please, if suggesting actions create a relevant issue and link it here.

**Comment by SaintFenix** [comment]
#375 and #377 

Would be feature requests in this territory.

**Comment by a-kenji** [comment]
@SaintFenix, Thanks I would say #368 doesn't fit here though,
we already have the action for it `SwitchToMode: Locked`,
but we don't have the possibility of configuring zellij to start in the locked mode yet,

**Comment by SaintFenix** [comment]
@a-kenji I understand now, I'll keep with that.

I've made another one here for tmux compatibility: #398

**Comment by a-kenji** [comment]
Dispatching keybound actions into plugins #662 .
