### ISSUE TITLE
[Feature Request] Send text/buffer to pane

### ISSUE THREAD

**Issue by uncomfyhalomacro** [zellij-org/zellij#809]
# Feature Request Description

Sends text directly to another pane on an existing session. As simple as that.
Example command:  `zellij send-text --session <name> --pane <index> <text or command that shows text like 'cat'>`

## Use cases

1. Editor plugins (e.g. vim-slime for neovim and vim)
2. Saving a finite list of buffers so it can be used later.
3. REPL Workflow based on point (1). For users of Julia, Python, R, and other languages that has a REPL.
4. Save a mouse selection to the list of buffers (?)

An example for points 1 and 3 in tmux with vim-slime plugin for neovim:

https://user-images.githubusercontent.com/66054069/139166920-87ed9774-e336-4455-af3d-8aaddf052bf0.mp4

### Todo

- [ ] 1. Implement the cli command somewhere in https://github.com/zellij-org/zellij/blob/main/zellij-utils/src/cli.rs#L51 (in progress)
- [ ] 2. Add the handler somewhere in https://github.com/zellij-org/zellij/blob/main/src/main.rs#L85 (idle)
- [ ] 3. Create a new instruction for the command (passive)
- [ ] 4. Set the environment variables in each session/pane/tab to facilitate doing this when you're inside Zellij (last to do)

**Comment by uncomfyhalomacro** [comment]
Closing. Implemented in https://github.com/zellij-org/zellij/pull/1265

**Comment by aris-mav** [comment]
> Closing. Implemented in [#1265](https://github.com/zellij-org/zellij/pull/1265)

Hello, sorry for necroposting, but I'm curious, how would you send some selected text from one pane with the editor (say, nvim or helix) to another pane with a julia or python repl?
